### ISSUE TITLE
Profile the code on the test case

### ISSUE THREAD

**Issue by jiqicn** [ODISSEI-School-Choice/school-choice#1]

**Comment by maltelueken** [comment]
Profiling looks good so far. Next steps:
- Looking into expensive numpy calls
- Replacing list comprehensions with numpy operations
- Looking into data structures of objects and operations performed on them (i.e., mismatch between operation and data structure)

**Comment by jiqicn** [comment]
Redo the profiling on the updated code.

**Comment by jiqicn** [comment]
Something abnormal was noticed while profiling the code. 
- For the benchmark case, the training is converged after step 51.
- Divide by zero warning found for the first and second steps.
- The second step takes much longer than the others.

**Comment by jiqicn** [comment]
Profiling results are shown in the figures below:

# Icicle plot generated by snakeviz
![icicle](https://github.com/ODISSEI-School-Choice/school-choice/blob/gitlabmaster/profile/profile_icicle.png?raw=true)

# Dot graph generated by gprof2dot
![dots](https://github.com/ODISSEI-School-Choice/school-choice/blob/gitlabmaster/profile/gprof_dots.png?raw=true)
