### ISSUE TITLE
Alternatives to Python Pickle for storing agents

### ISSUE THREAD

**Issue by jiqicn** [ODISSEI-School-Choice/school-choice#4]
Python Pickle is not considered a recommended way of data storage for some reasons, e.g.: 
- Not able to automatically handle package versions
- Enormous memory usage while loading pickle files (Python objects can be very big in memory, and they get very compact representation when pickled)

Thus, it would be ideal to find an alternative format for storing agents (or their information).

**Comment by jiqicn** [comment]
Worth looking at this benchmark of Python serialization tools: https://voidfiles.github.io/python-serialization-benchmark/.

**Comment by jiqicn** [comment]
Regarding to this [blog](https://docs.python-guide.org/scenarios/serialization/), people can consider YAML, JSON, and XML as the file format while serializing nested data (in our case, agent objects).

**Comment by jiqicn** [comment]
A cookbook for choosing the most suitable JSON package, with tests and benchmarks: https://pythonspeed.com/articles/faster-json-library/.

**Comment by maltelueken** [comment]
Looks quite good! Perhaps you could look into:
- Run-length encoding (RLE) for reducing the size of objects to be stored
- Try different encoders/decoders for json
- Look into storing tensor objects
